### PR TITLE
fixed voting options accordion display

### PR DESCRIPTION
**Pull request by tif03**

### CODE REVIEW

**Review by Remus287 — APPROVED** [review]
Tested page updates locally
all content present/correct
all links work
styling problem fixed

code looks good

**Review by celineboudaie — APPROVED** [review]
The changes for accordion style look good to me

**Review by mochiakku — CHANGES_REQUESTED** [review]
Looks good, please remember to change the PR to merge into dev (which needs to be updates to catch up to main) instead!

**Review by gamurphy — APPROVED** [review]
Everything works as it should & the styling has been properly updated.

**Comment by Remus287** [comment]
need to merge into dev first then to PR into main

**Pull request closed without merging**
